version: '1'

services:
  angular-client:
    build: angular-client
    ports:
      - "4200:4200"
    volumes:
      - ./angular-client/:/usr/src/app

  express-server:
    build: express-server
    ports:
      - "3000:3000"
    volumes:

      - ./express-server/:/usr/src/app
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"